export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESSFULL = 'AUTH_SUCCESSFULL';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_USERPROFILE = 'SET_USERPROFILE';
export const CHECK_AUTH_STATUS = 'CHECK_AUTH_STATUS';

export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const PAYEE_DETAILS_START = 'PAYEE_DETAILS_START'
export const PAYEE_DETAILS_SUCCESS = 'PAYEE_DETAILS_SUCCESS'
export const PAYEE_DETAILS_FAILED = 'PAYEE_DETAILS_FAILED'

export const TRANSFER_START = 'TRANSFER_START';
export const TRANSFER_SUCCESS = 'TRANSFER_SUCCESS';
export const TRANSFER_FAILED = 'TRANSFER_FAILED';
export const CLEAR_TRANSFER = 'CLEAR_TRANSFER'

export const SEARCH_PAYEE_START = 'SEARCH_PAYEE';
export const SEARCH_PAYEE = 'SEARCH_PAYEE_START';

export const ADD_PAYEE = 'ADD_PAYEE';
export const ADD_PAYEE_SUCCESS = 'ADD_PAYEE_SUCCESS';
export const ADD_PAYEE_FAILED = 'ADD_PAYEE_FAILED';

export const GET_PAYMENT_HISTORY_START = 'GET_PAYMENT_HISTORY_START';
export const GET_PAYMENT_HISTORY_SUCCESS = 'GET_PAYMENT_HISTORY_SUCCESS';
export const GET_PAYMENT_HISTORY_FAILED = 'GET_PAYMENT_HISTORY_FAILED';